/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cidesi;

import static cidesi.PanelP.uss;
import codigo.conexion;
//import static codigo.conexion.usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author salinas
 */
public class configuracion extends javax.swing.JInternalFrame {
Connection conn=conexion.Coneccion();

    /**
     * Creates new form configuracion
     */
    public configuracion() {
        initComponents();
        
        musuario.setEditable(false);
        mcontraseña.setEditable(false);
        mcontraseña2.setEditable(false);
        error.setVisible(false);
        cambiar.setEnabled(false);
        String usua=PanelP.uss.getText();
        String sql="select*from usuario where nombre='"+usua+"'";
        Statement sent;
    try {
        sent = conn.createStatement();
        ResultSet rs=sent.executeQuery(sql);
        rs.next();
        ID.setText(rs.getString("id"));
     musuario.setText(rs.getString("nombre"));
     mcontraseña.setText(rs.getString("contraseña"));
     mcontraseña2.setText(rs.getString("contraseña"));
    } catch (SQLException ex) {
        Logger.getLogger(configuracion.class.getName()).log(Level.SEVERE, null, ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        musuario = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        cambiar = new javax.swing.JButton();
        mcontraseña = new javax.swing.JPasswordField();
        mcontraseña2 = new javax.swing.JPasswordField();
        error = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();

        setClosable(true);
        setTitle("CONFIGURAR USUARIO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("USUARIO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CONTRASEÑA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CONTRASEÑA");

        jRadioButton1.setText("MODIFICAR");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        cambiar.setText("ACEPTAR");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });

        mcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mcontraseñaKeyReleased(evt);
            }
        });

        mcontraseña2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mcontraseña2KeyReleased(evt);
            }
        });

        error.setFont(new java.awt.Font("MV Boli", 0, 11)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 51));
        error.setText("CONTRASEÑA NO COINCIDE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("N.USUARIO");

        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mcontraseña)
                                .addComponent(musuario)
                                .addComponent(mcontraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(cambiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jRadioButton1)
                .addGap(27, 27, 27)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(musuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mcontraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(cambiar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed

        
        int fila =Integer.valueOf(ID.getText());

        String sql="Update usuario set nombre=?,contraseña=? where id=?";
        try {
            PreparedStatement sent=conn.prepareCall(sql);
            sent.setString(1,musuario.getText());
            sent.setString(2,mcontraseña.getText());
            sent.setString(3,ID.getText());
            int n=sent.executeUpdate();
            if(n>0){
                uss.setText(musuario.getText());
            JOptionPane.showMessageDialog(null,"Usuario modificado");
            this.dispose();
            }else{
            JOptionPane.showMessageDialog(null,"Error bruto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
       
            
    }//GEN-LAST:event_cambiarActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
         musuario.setEditable(true);
        mcontraseña.setEditable(true);
        mcontraseña2.setEditable(true);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void mcontraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mcontraseñaKeyReleased
if(mcontraseña.getText().equals(mcontraseña2.getText())){
cambiar.setEnabled(true);
    error.setVisible(false);
}else{
cambiar.setEnabled(false);
error.setVisible(true);

}
    }//GEN-LAST:event_mcontraseñaKeyReleased

    private void mcontraseña2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mcontraseña2KeyReleased
if(mcontraseña2.getText().equals(mcontraseña.getText())){
cambiar.setEnabled(true);
    error.setVisible(false);
}else{
cambiar.setEnabled(false);
error.setVisible(true);
}
    }//GEN-LAST:event_mcontraseña2KeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton cambiar;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPasswordField mcontraseña;
    private javax.swing.JPasswordField mcontraseña2;
    private javax.swing.JTextField musuario;
    // End of variables declaration//GEN-END:variables
}
