/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cidesi;

import codigo.conexion;
import codigo.denominaciones;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.lang.Integer;
import java.lang.String;
import java.lang.ClassCastException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import static cidesi.PanelP.RealizarBanco;

/**
 *
 * @author HP
 */
public class monto extends javax.swing.JInternalFrame {

    Connection conn = conexion.Coneccion();

    /**
     * Creates new form monto
     */
    public monto() {
        initComponents();

        cero();
        cantidad();
        bloquear();
    }

    void cantidad() {
        String sql = "select*from denominaciones ";
        try {
            Statement sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
            lmil.setText(rs.getString("a1000"));
            lquinientos1.setText(rs.getString("a500"));
            ldoscientos.setText(rs.getString("a200"));
            lcien.setText(rs.getString("a100"));
            lcincuenta.setText(rs.getString("a50"));
            lveinte.setText(rs.getString("a20"));
            lmonedaveinte.setText(rs.getString("M20"));
            ldiez.setText(rs.getString("a10"));
            lcinco.setText(rs.getString("a5"));
            ldos1.setText(rs.getString("a2"));
            luno.setText(rs.getString("a1"));
            lcentavos5.setText(rs.getString("C50"));
            lcentavos2.setText(rs.getString("C20"));
            lcentavos1.setText(rs.getString("C10"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro en los label " + e);
        }
    }

    void bloquear() {

    }

    void cero() {

        mveinte.setText("0");
        diez.setText("0");
        cinco.setText("0");
        dos.setText("0");
        uno.setText("0");
        mcincuenta.setText("0");
        pveinte.setText("0");
        pdiez.setText("0");

    }

    void todo() {
        denominaciones l = new denominaciones();
        l.totalC();

    }

    /*

     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mil = new javax.swing.JComboBox<>();
        quinientos = new javax.swing.JComboBox<>();
        doscientos = new javax.swing.JComboBox<>();
        cien = new javax.swing.JComboBox<>();
        cincuenta = new javax.swing.JComboBox<>();
        veinte = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mveinte = new javax.swing.JTextField();
        diez = new javax.swing.JTextField();
        cinco = new javax.swing.JTextField();
        dos = new javax.swing.JTextField();
        uno = new javax.swing.JTextField();
        mcincuenta = new javax.swing.JTextField();
        pdiez = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pveinte = new javax.swing.JTextField();
        ldoscientos = new javax.swing.JLabel();
        lmil = new javax.swing.JLabel();
        lquinientos1 = new javax.swing.JLabel();
        lcincuenta = new javax.swing.JLabel();
        lcien = new javax.swing.JLabel();
        lmonedaveinte = new javax.swing.JLabel();
        lveinte = new javax.swing.JLabel();
        ldiez = new javax.swing.JLabel();
        lcinco = new javax.swing.JLabel();
        luno = new javax.swing.JLabel();
        ldos1 = new javax.swing.JLabel();
        lcentavos5 = new javax.swing.JLabel();
        lcentavos1 = new javax.swing.JLabel();
        lcentavos2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("BILLETES");

        jLabel2.setText("MONEDAS");

        jLabel3.setText("1000");

        jLabel4.setText("500");

        jLabel5.setText("200");

        jLabel6.setText("100");

        jLabel7.setText("50");

        jLabel8.setText("20");

        mil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        mil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milActionPerformed(evt);
            }
        });

        quinientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        doscientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cincuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        veinte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel9.setText("05");

        jLabel10.setText("02");

        jLabel11.setText("01");

        jLabel13.setText(".50");

        jLabel14.setText(".10");

        jLabel15.setText("10");

        jLabel16.setText("20");

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText(".20");

        ldoscientos.setForeground(new java.awt.Color(153, 0, 0));

        lmil.setForeground(new java.awt.Color(153, 0, 0));

        lquinientos1.setForeground(new java.awt.Color(153, 0, 0));

        lcincuenta.setForeground(new java.awt.Color(153, 0, 0));

        lcien.setForeground(new java.awt.Color(153, 0, 0));

        lmonedaveinte.setForeground(new java.awt.Color(153, 0, 0));

        lveinte.setForeground(new java.awt.Color(153, 0, 0));

        ldiez.setForeground(new java.awt.Color(153, 0, 0));

        lcinco.setForeground(new java.awt.Color(153, 0, 0));

        luno.setForeground(new java.awt.Color(153, 0, 0));

        ldos1.setForeground(new java.awt.Color(153, 0, 0));

        lcentavos5.setForeground(new java.awt.Color(153, 0, 0));

        lcentavos1.setForeground(new java.awt.Color(153, 0, 0));

        lcentavos2.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doscientos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cincuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(veinte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mil, 0, 57, Short.MAX_VALUE)
                            .addComponent(quinientos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lmil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lquinientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ldoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(8, 8, 8)
                                .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mveinte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(diez)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cinco, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                        .addComponent(dos, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lmonedaveinte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ldiez, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ldos1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(luno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mcincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lcentavos5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pveinte, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lcentavos2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pdiez, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lcentavos1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lveinte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lmil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel3)
                        .addComponent(mil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(mveinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mcincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lmonedaveinte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lcentavos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(quinientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(diez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(pveinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lcentavos2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(doscientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(pdiez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcentavos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ldoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ldiez, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lquinientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel6)
                                        .addComponent(cien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ldos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lcien, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(veinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lcincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lveinte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(luno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void milActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
///////////////////////////////////////////////////        

        denominaciones d = new denominaciones();
        float banco = d.banco();

        try {
            String sql = "select*from denominaciones where id=1";
            Statement sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            rs.next();
/// Mandar a string los datos de la base de datos
            String v1 = rs.getString("a1000");
            String v2 = rs.getString("a500");
            String v3 = rs.getString("a200");
            String v4 = rs.getString("a100");
            String v5 = rs.getString("a50");
            String v6 = rs.getString("a20");
            String v7 = rs.getString("M20");
            String v8 = rs.getString("a10");
            String v9 = rs.getString("a5");
            String v10 = rs.getString("a2");
            String v11 = rs.getString("a1");
            String v12 = rs.getString("C50");
            String v13 = rs.getString("C20");
            String v14 = rs.getString("C10");
/////////////////////////Convertir los v?? a int
            int vl1 = Integer.valueOf(v1);
            int vl2 = Integer.valueOf(v2);
            int vl3 = Integer.valueOf(v3);
            int vl4 = Integer.valueOf(v4);
            int vl5 = Integer.valueOf(v5);
            int vl6 = Integer.valueOf(v6);
            int vl7 = Integer.valueOf(v7);
            int vl8 = Integer.valueOf(v8);
            int vl9 = Integer.valueOf(v9);
            int vl10 = Integer.valueOf(v10);
            int vl11 = Integer.valueOf(v11);
            int vl12 = Integer.valueOf(v12);
            int vl13 = Integer.valueOf(v13);
            int vl14 = Integer.valueOf(v14);
/////////// Mandar a string los datos del usuario
            String s1 = (String) mil.getSelectedItem();
            String s2 = (String) quinientos.getSelectedItem();
            String s3 = (String) doscientos.getSelectedItem();
            String s4 = (String) cien.getSelectedItem();
            String s5 = (String) cincuenta.getSelectedItem();
            String s6 = (String) veinte.getSelectedItem();
            String s7 = mveinte.getText();
            String s8 = diez.getText();
            String s9 = cinco.getText();
            String s10 = dos.getText();
            String s11 = uno.getText();
            String s12 = mcincuenta.getText();
            String s13 = pveinte.getText();
            String s14 = pdiez.getText();
////////////////////convertirlos a enteros
            int l1 = Integer.valueOf(s1);
            int l2 = Integer.valueOf(s2);
            int l3 = Integer.valueOf(s3);
            int l4 = Integer.valueOf(s4);
            int l5 = Integer.valueOf(s5);
            int l6 = Integer.valueOf(s6);
            int l7 = Integer.valueOf(s7);
            int l8 = Integer.valueOf(s8);
            int l9 = Integer.valueOf(s9);
            int l10 = Integer.valueOf(s10);
            int l11 = Integer.valueOf(s11);
            int l12 = Integer.valueOf(s12);
            int l13 = Integer.valueOf(s13);
            int l14 = Integer.valueOf(s14);
////////////////////// agregado

            int smil = l1 * 1000;
            int squinientos = l2 * 500;
            int sdoscientos = l3 * 200;
            int scien = l4 * 100;
            int scincuenta = l5 * 50;
            int sveinte = l6 * 20;
            int smveinte = l7 * 20;
            int sdiez = l8 * 10;
            int scinco = l9 * 5;
            int sdos = l10 * 2;
            int suno = l11 * 1;
            float sccincuenta = l12 * .5f;
            float scveinte = l13 * .2f;
            float scdiez = l14 * .1f;
            float total = smil + squinientos + sdoscientos + scien + scincuenta + sveinte + smveinte + sdiez + scinco
                    + sdos + suno + scveinte + sccincuenta + scdiez;

//float importe=Float.valueOf(PanelP.importe.getText())+0;]
            try {
                if (jLabel17.getText().equals("Devoluciones")) {
                    float monto = Float.valueOf(PanelP.importe.getText());
                    if (total == monto) {
                        try {
/////////////////Convertir a String 
                            String total1 = String.valueOf(l1 + vl1);
                            String total2 = String.valueOf(l2 + vl2);
                            String total3 = String.valueOf(l3 + vl3);
                            String total4 = String.valueOf(l4 + vl4);
                            String total5 = String.valueOf(l5 + vl5);
                            String total6 = String.valueOf(l6 + vl6);
                            String total7 = String.valueOf(l7 + vl7);
                            String total8 = String.valueOf(l8 + vl8);
                            String total9 = String.valueOf(l9 + vl9);
                            String total10 = String.valueOf(l10 + vl10);
                            String total11 = String.valueOf(l11 + vl11);
                            String total12 = String.valueOf(l12 + vl12);
                            String total13 = String.valueOf(l13 + vl13);
                            String total14 = String.valueOf(l14 + vl14);
                            String sqll = "Update denominaciones set a1000=?,a500=?,a200=?,a100=?,a50=?,a20=?,"
                                    + "M20=?,a10=?,a5=?,a2=?,a1=?,C50=?,C20=?,C10=? where id=1";
                            PreparedStatement pss = conn.prepareCall(sqll);
                            pss.setString(1, total1);
                            pss.setString(2, total2);
                            pss.setString(3, total3);
                            pss.setString(4, total4);
                            pss.setString(5, total5);
                            pss.setString(6, total6);
                            pss.setString(7, total7);
                            pss.setString(8, total8);
                            pss.setString(9, total9);
                            pss.setString(10, total10);
                            pss.setString(11, total11);
                            pss.setString(12, total12);
                            pss.setString(13, total13);
                            pss.setString(14, total14);
                            int n = pss.executeUpdate();

                            if (n > 0) {
                                String mn = "select*from cheque where id=1";
                                Statement l = conn.createStatement();
                                ResultSet mdd = l.executeQuery(mn);
                                mdd.next();

                                String tog = String.valueOf(Float.valueOf(mdd.getString("gastos")) - total);
                                String actualizar = "Update cheque set gastos=? where id=1";
                                PreparedStatement preparar = conn.prepareCall(actualizar);
                                preparar.setString(1, tog);
                                int solo = preparar.executeUpdate();
                                todo();
                                JOptionPane.showMessageDialog(null, "Valores guardados" + total);
                                PanelP.jButton3.setEnabled(true);
                                this.dispose();
                            }

                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "error devolucion" + ex);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "denominaciones no coinciden \n deberia ser"
                                + ":" + monto + " y tu  en denominaciones colocaste:" + total);
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreo devolucion" + e);
            }
            /*
if(jLabel17.getText().equals("Devoluciones")){
       String s="select*from cheque where id=1";
       Statement mn=conn.createStatement();
       ResultSet rd=mn.executeQuery(s);
       rd.next();
       int caja=Integer.parseInt(rd.getString("gastos"));
       float todos=caja-total;
       
       String to="Update cheque set gastos=? where id=1";
       PreparedStatement l=conn.prepareCall(to);
       String t=String.valueOf(todos);
       l.setString(1,t);
       int pd=l.executeUpdate();
       
       
           }*/

            if (jLabel17.getText().equals("Retiro")) {

                float monto = Float.valueOf(PanelP.monto.getText());
                float todo = banco - monto;

                if (total == monto) {
                    if (todo >= 0) {
/////////////////Convertir a String 
                        String total1 = String.valueOf(l1 + vl1);
                        String total2 = String.valueOf(l2 + vl2);
                        String total3 = String.valueOf(l3 + vl3);
                        String total4 = String.valueOf(l4 + vl4);
                        String total5 = String.valueOf(l5 + vl5);
                        String total6 = String.valueOf(l6 + vl6);
                        String total7 = String.valueOf(l7 + vl7);
                        String total8 = String.valueOf(l8 + vl8);
                        String total9 = String.valueOf(l9 + vl9);
                        String total10 = String.valueOf(l10 + vl10);
                        String total11 = String.valueOf(l11 + vl11);
                        String total12 = String.valueOf(l12 + vl12);
                        String total13 = String.valueOf(l13 + vl13);
                        String total14 = String.valueOf(l14 + vl14);
                        String sqll = "Update denominaciones set a1000=?,a500=?,a200=?,a100=?,a50=?,a20=?,"
                                + "M20=?,a10=?,a5=?,a2=?,a1=?,C50=?,C20=?,C10=? where id=1";
                        PreparedStatement pss = conn.prepareCall(sqll);
                        pss.setString(1, total1);
                        pss.setString(2, total2);
                        pss.setString(3, total3);
                        pss.setString(4, total4);
                        pss.setString(5, total5);
                        pss.setString(6, total6);
                        pss.setString(7, total7);
                        pss.setString(8, total8);
                        pss.setString(9, total9);
                        pss.setString(10, total10);
                        pss.setString(11, total11);
                        pss.setString(12, total12);
                        pss.setString(13, total13);
                        pss.setString(14, total14);
                        int n = pss.executeUpdate();
                        if (n > 0) {
                            try {
                                todo();
                                JOptionPane.showMessageDialog(null, "Valores guardados" + total);
                                String s = "select*from cheque where id=1";
                                Statement mn = conn.createStatement();
                                ResultSet rd = mn.executeQuery(s);
                                rd.next();
                                float caja = Float.valueOf(rd.getString("banco"));
                                float todos = caja - total;

                                String to = "Update cheque set banco=? where id=1";
                                PreparedStatement l = conn.prepareCall(to);
                                String t = String.valueOf(todos);
                                l.setString(1, t);
                                int pd = l.executeUpdate();
                                PanelP.RealizarBanco.setEnabled(true);
                                this.dispose();
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "1234 " + e);
                            }
                        }

                    } else {

                        JOptionPane.showMessageDialog(null, "Saldo insuficiente, solo tiene para retirar $" + banco);

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "denominaciones no coinciden \n deberia ser"
                            + ":" + monto + " y tu  en denominaciones colocaste:" + total);
                }

            }
            if (jLabel17.getText().equals("Prestamos")) {
                try {
                    float importe = Float.valueOf(PanelP.importe.getText());
                    if (total == importe) {

//////////suma
                        int to1 = vl1 - l1;
                        int to2 = vl2 - l2;
                        int to3 = vl3 - l3;
                        int to4 = vl4 - l4;
                        int to5 = vl5 - l5;
                        int to6 = vl6 - l6;
                        int to7 = vl7 - l7;
                        int to8 = vl8 - l8;
                        int to9 = vl9 - l9;
                        int to10 = vl10 - l10;
                        int to11 = vl11 - l11;
                        int to12 = vl12 - l12;
                        int to13 = vl13 - l13;
                        int to14 = vl14 - l14;
/////////////////Convertir a String 
                        String total1 = String.valueOf(to1);
                        String total2 = String.valueOf(to2);
                        String total3 = String.valueOf(to3);
                        String total4 = String.valueOf(to4);
                        String total5 = String.valueOf(to5);
                        String total6 = String.valueOf(to6);
                        String total7 = String.valueOf(to7);
                        String total8 = String.valueOf(to8);
                        String total9 = String.valueOf(to9);
                        String total10 = String.valueOf(to10);
                        String total11 = String.valueOf(to11);
                        String total12 = String.valueOf(to12);
                        String total13 = String.valueOf(to13);
                        String total14 = String.valueOf(to14);
                        String sqll = "Update denominaciones set a1000=?,a500=?,a200=?,a100=?,a50=?,a20=?,"
                                + "M20=?,a10=?,a5=?,a2=?,a1=?,C50=?,C20=?,C10=? where id=1";
                        PreparedStatement pss = conn.prepareCall(sqll);
                        pss.setString(1, total1);
                        pss.setString(2, total2);
                        pss.setString(3, total3);
                        pss.setString(4, total4);
                        pss.setString(5, total5);
                        pss.setString(6, total6);
                        pss.setString(7, total7);
                        pss.setString(8, total8);
                        pss.setString(9, total9);
                        pss.setString(10, total10);
                        pss.setString(11, total11);
                        pss.setString(12, total12);
                        pss.setString(13, total13);
                        pss.setString(14, total14);
                        int n = pss.executeUpdate();
                        if (n > 0) {
                            todo();
                            JOptionPane.showMessageDialog(null, "Valores guardados " + total);
                            String s = "select*from cheque where id=1";
                            Statement mn = conn.createStatement();
                            ResultSet rd = mn.executeQuery(s);
                            rd.next();
                            float caja = Integer.parseInt(rd.getString("gastos"));
                            float todos = caja + total;

                            String to = "Update cheque set gastos=? where id=1";
                            PreparedStatement l = conn.prepareCall(to);
                            String t = String.valueOf(todos);
                            l.setString(1, t);
                            int pd = l.executeUpdate();
                            PanelP.jButton3.setEnabled(true);
                            this.dispose();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "denominaciones no coinciden \n deberia ser"
                                + ":" + importe + " y tu  en denominaciones colocaste:" + total);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "error prestamos " + ex);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro aqui  " + e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cien;
    public static javax.swing.JTextField cinco;
    public static javax.swing.JComboBox<String> cincuenta;
    public static javax.swing.JTextField diez;
    public static javax.swing.JTextField dos;
    public static javax.swing.JComboBox<String> doscientos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lcentavos1;
    private javax.swing.JLabel lcentavos2;
    private javax.swing.JLabel lcentavos5;
    private javax.swing.JLabel lcien;
    private javax.swing.JLabel lcinco;
    private javax.swing.JLabel lcincuenta;
    private javax.swing.JLabel ldiez;
    private javax.swing.JLabel ldos1;
    private javax.swing.JLabel ldoscientos;
    private javax.swing.JLabel lmil;
    private javax.swing.JLabel lmonedaveinte;
    private javax.swing.JLabel lquinientos1;
    private javax.swing.JLabel luno;
    private javax.swing.JLabel lveinte;
    public static javax.swing.JTextField mcincuenta;
    public static javax.swing.JComboBox<String> mil;
    public static javax.swing.JTextField mveinte;
    public static javax.swing.JTextField pdiez;
    public static javax.swing.JTextField pveinte;
    public static javax.swing.JComboBox<String> quinientos;
    public static javax.swing.JTextField uno;
    public static javax.swing.JComboBox<String> veinte;
    // End of variables declaration//GEN-END:variables
}
